#
# defaults
#

inventory:
  hostname:     ~
  service:      ~
  machine:      ~
  
system:
  active:       1
# rootpw:       ''
  grubcmd:      'quiet nomodeset net.ifnames=0 biosdevname=0'
# timezone:     Etc/UTC
# release:      unknown
# kernver:      ''
# paranoid:     0
# aptproxy:     http://127.0.0.1:9080
  backports:    1
# extradebs:    0
# extralink:    http://debs.test.net
# packages:     [ ]
  sysctl:
    '15-ip_forward':      0
    '25-route_localnet':  0
    '95-disable_ipv6':    0

# swapfile:     /swap
# swapdize:     1024k


network:
  active:       1
# nameserver:   [ 8.8.8.8, 8.8.4.4 ]
# ethernet:     { }
# bridge:       { }
# shaper:
#   enabled:      0
#   ifbs:         1
#   link:         [ 100Mbit, 100Mbit ]
#   misc:         [  10Mbit,  10Mbit ]


firewall:
  active:       1
# type:         simple
# inline:       { }


monit:
  active:       1
# address:      127.0.0.1
# port:         2812
# cert:         ~
# auth:         monit:secret
# mmonit:       ''
  confs:
    'system':
      enabled:      1
#     name:         system

    'sensors':
      enabled:      0
#     name:         sensors


collectd:
  active:       1
# server:       0
# remote:       ~
# interface:    ~
# address:      ~
# port:         25826
# username:     ''
# password:     ''
  confs:
    'syslog':
      enabled:      1
#     name:         syslog

    'network':
      enabled:      1
#     name:         network

    'cpu':
      enabled:      1
#     name:         cpu

    'memory':
      enabled:      1
#     name:         memory

    'swap':    
      enabled:      1
#     name:         swap

    'load':    
      enabled:      1
#     name:         load

    'interface':
      enabled:      1
#     name:         interface

#   'netlink':
#     enabled:      0
#     name:         netlink

    'rrdtool': 
      enabled:      1
#     name:         rrdtool

  monit:
    enabled:      1
#   timeout:      10


rsyslog:
  active:       1
# confs:        { }
  monit:
    enabled:      1


logrotate:
  active:       1
  confs:
    'apt':
      enabled:      1
#     name:         apt

    'aptitude':
      enabled:      1
#     name:         aptitude

    'dpkg':
      enabled:      1
#     name:         dpkg

    'rsyslog':
      enabled:      1
#     name:         rsyslog

#   'monit':
#     enabled:      1
#     name:         monit

#   'collectd':
#     enabled:      1
#     name:         collectd


cron:
  active:       1
# crontab:      { }
# hourly:       { }
# daily:        { }
# weekly:       { }
# monthly:      { }
  monit:
    enabled:      1


openssh:
  active:       1
# address:      0.0.0.0
# port:         22
  monit:
    enabled:      1


ntp:
  active:       1
  monit:
    enabled:      1


qemukvm:
  active:       0
  monit:
    enabled:      1


iperf:
  active:       0
# server:       0
# address:      0.0.0.0
# port:         5281
# targets:      [ ]
  monit:
    enabled:      1
#   timeout:      10


dnsmasq:
  active:       0
# address:      127.0.0.1
# interface:    lo
# port:         53
# upstream:     [ 8.8.8.8, 8.8.4.4 ]
# conf:         { }
  monit:
    enabled:      1
#   timeout:      10


unbound:
  active:       0
# address:      127.0.0.1
# port:         53
# allowed:      [ 127.0.0.1/8 ]
  conf:
    'qname-minimisation':
      enabled:      1
#     name:         qname-minimisation

    'root-auto-trust-anchor-file':
      enabled:      1
#     name:         root-auto-trust-anchor-file

  monit:
    enabled:      1
#   timeout:      10


pki:
  active:       0
  options:      '--agree-tos --webroot -w /var/www/default'
  certs:        { }


nginx:
  active:       0
# package:      nginx-light
# address:      127.0.0.1
# port:         80
# ssl_port:     443
# resolver:     [ 8.8.8.8, 8.8.4.4 ]
  conf:
    'file_cache':   1
    'gzip':         1
    'resolver':     0
    'ssl':          1
    'cloudflare':   0

# snippets:     { }
# secrets:      { }

  sites:
    'default':
      enabled:      1
#     name:         default
#     domain:       '""'
#     address:      127.0.0.1
#     port:         80
#     ssl_port:     443
#     cert:         ~
 
  monit:
    enabled:      1
#   timeout:      10


mysql:
  active:       0
# address:      127.0.0.1
# port:         3306
# rootpw:       'secret'
# conf:         { }
  monit:
    enabled:      1


redis:
  active:       0
# address:      127.0.0.1
# port:         6379
  monit:
    enabled:      1
#   timeout:      10
#   dumpsize:     100


postfix:
  active:       0
  monit:
    enabled:      1


rblcheck:
  active:       0
# hosts:        [ 127.0.0.1 ]
# lists:        [ zen.spamhaus.org ]
  monit:
    enabled:      1
#   timeout:      10


mmonit:
  active:       0
# version:      3.7.2
# platform:     linux-x64
# path:         /opt/mmonit
# address:      0.0.0.0
# port:         3127
# cert:         ~
# schema:       postgresql://monit:monit@127.0.0.1/mmonit
# owner:        Unknown
# lecense:      none


rsync:
  active:       0
# address:      ~
# port:         873
# storage:      /var/www/stuff
  monit:
    enabled:      1
#   timeout:      10


gitweb:
  active:       0
# projectroot:  /var/lib/git
# site_name:    Simple


freight:
  active:       0
# libdir:       /var/lib/freight
# cachedir:     /var/www/freight
# origin:       extradebs
# label:        Extradebs
# gpgkey:       build@extradebs


cgp:
  active:       0
# distrib:      https://github.com/pommi/CGP.git
# workdir:      /var/www/cgp


