#
# Configuration Management Database
#

system:
  active:       1
# rootpw:       ''
  grubcmd:      'quiet nomodeset net.ifnames=0 biosdevname=0'
# timezone:     Etc/UTC
# release:      debian-stretch
# kernver:      ''
# paranoid:     0
# aptproxy:     http://127.0.0.1:9080
  backports:    1
# extradebs:    0
# extralink:    http://debs.test.net
# packages:     [ ]
# swapfile:     /swap
# swapdize:     1024k

network:
  active:       1
# forward:      0
# resolver:     [ 8.8.8.8, 8.8.4.4 ]
# ethernet:     { }
# bridge:       { }

firewall:
  active:       1
# type:         none
# restart:      1

shaper:
  active:       0
# ifb:          0
# link:         [ 100Mbit, 100Mbit ]
# priv:         [  10Mbit,  90Mbit ]
# misc:         [   1Mbit,   2Mbit ]

syslog:
  active:       1
# restart:      1
# rsyslog:      { }
  logrotate:
    'apt':        1
    'aptitude':   1
    'dpkg':       1
    'rsyslog':    1

  monit:
    enabled:      1

cron:
  active:       1
# restart:      1
# crontab:      { }
# hourly:       { }
# daily:        { }
# weekly:       { }
# monthly:      { }
  monit:
    enabled:      1

openssh:
  active:       1
# address:      [ 0.0.0.0 ]
# port:         22
# restart:      1
  monit:
    enabled:      1

ntp:
  active:       1
# restart:      1
  monit:
    enabled:      1

iperf:
  active:       0
# restart:      1
# server:       0
# address:      0.0.0.0
# port:         5281
# targets:      [ ]
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         5281
#   timeout:      10

qemukvm:
  active:       0
# restart:      1

dnsmasq:
  active:       0
# restart:      1
# resolver:     1
# address:      [ 127.0.0.1 ]
# interface:    [ lo ]
# port:         53
# upstream:     [ 8.8.8.8, 8.8.4.4 ]
# conf:         { }
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         53
#   timeout:      10

unbound:
  active:       0
# restart:      1
# resolver:     0
# address:      [ 127.0.0.1 ]
# port:         53
# allowed:      [ 127.0.0.1/8 ]
  conf:
    'qname-minimisation': 1
    'root-auto-trust-anchor-file': 1

  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         53
#   timeout:      10

nginx:
  active:       0
# restart:      1
  conf:
    'cache':      1
    'gzip':       1
    'resolver':   1
    'ssl':        0
    'cloudflare': 0

# snippets:     { }
# secrets:      { }

  sites:
    'default':
      enabled:      1
      address:      [ 127.0.0.1 ]
#     port:         80
 
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         80
#   timeout:      10

mysql:
  active:       0
# restart:      1
# address:      127.0.0.1
# port:         3306
# rootpw:       'secret'
# conf:         { }
  monit:
    enabled:      1

redis:
  active:       0
# restart:      1
# address:      [ 127.0.0.1 ]
# port:         6379
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         6379
#   timeout:      10
#   dumpsize:     100

postfix:
  active:       0
# restart:      1

rblcheck:
  active:       0
# hosts:        [ 127.0.0.1 ]
# lists:        [ zen.spamhaus.org ]
  monit:
    enabled:      1
#   timeout:      10

monit:
  active:       1
# restart:      1
# address:      127.0.0.1
# port:         2812
# auth:         monit:secret
# mmonit:       "https://monit:secret\@monit.test.net:3127/collector"
  confs:
    'system':
      enabled:      1

    'sensors':
      enabled:      0

mmonit:
  active:       0
# restart:      1
# version:      3.7.1
# platform:     linux-x64
# path:         /opt/mmonit
# address:      0.0.0.0
# port:         3127
# schema:       mysql://monit:monit@127.0.0.1/mmonit
# owner:        Unknown
# lecense:      none

collectd:
  active:       0
# restart:      1
# server:       0
# interval:     60
# remote:       graph.test.net
# address:      0.0.0.0
# port:         25826
# interface:    eth0
# username:     stats
# password:     'secret'
  confs:
    'syslog':
      enabled:      1

    'network':
      enabled:      1

    'cpu':
      enabled:      1

    'memory':
      enabled:      1

    'swap':    
      enabled:      1

    'load':    
      enabled:      1

    'interface':
      enabled:      1

#   'netlink':
#     enabled:      0

    'rrdtool': 
      enabled:      1

rsync:
  active:       0
# restart:      1
# address:      127.0.0.1
# port:         873
# storage:      /var/www/stuff

gitweb:
  active:       0
# projectroot:  /var/lib/git
# site_name:    Simple

freight:
  active:       0
# libdir:       /var/lib/freight
# cachedir:     /var/www/freight
# origin:       extradebs
# label:        Extradebs
# gpgkey:       build@extradebs

collectdweb:
  active:       0
# restart:      1
# workdir:      /var/www/collectd-web

