#
# defaults
#

inventory:
  hostname:     ~
  service:      ~
  machine:      ~
  
system:
  active:       1
# rootpw:       ''
  grubcmd:      'quiet nomodeset net.ifnames=0 biosdevname=0'
# timezone:     Etc/UTC
# release:      unknown
# kernver:      ''
# paranoid:     0
# aptproxy:     http://127.0.0.1:9080
# backports:    0
# extradebs:    0
# extralink:    http://debs.test.net
# packages:     [ ]
  sysctl:
    'ip_forward':
      enabled:      0
      name:         '15-ip_forward'

    'route_localnet':
      enabled:      0
      name:         '25-route_localnet'

    'disable_ipv6':
      enabled:      0
      name:         '95-disable_ipv6':

# swapfile:     /swap
# swapdize:     1024k

network:
  active:       1
# nameserver:   [ 8.8.8.8, 8.8.4.4 ]
# ethernet:     { }
# bridge:       { }
# shaper:
#   enabled:      0
#   ifbs:         1
#   link:         [ 100Mbit, 100Mbit ]
#   misc:         [  10Mbit,  10Mbit ]

firewall:
  active:       1
# type:         none
# inline:       { }

monit:
  active:       1
# address:      127.0.0.1
# port:         2812
# auth:         monit:secret
# mmonit:       https://monit:secret@monit.test.net:3127/collector
  confs:
    'system':
      enabled:      1
#     name:         system

    'sensors':
      enabled:      0
#     name:         sensors

collectd:
  active:       0
# server:       0
# interval:     60
# remote:       graph.test.net
# interface:    eth0
# address:      0.0.0.0
# port:         25826
# username:     stats
# password:     'secret'
  confs:
    'syslog':
      enabled:      1
#     name:         syslog

    'network':
      enabled:      1
#     name:         network

    'cpu':
      enabled:      1
#     name:         cpu

    'memory':
      enabled:      1
#     name:         memory

    'swap':    
      enabled:      1
#     name:         swap

    'load':    
      enabled:      1
#     name:         load

    'interface':
      enabled:      1
#     name:         interface

#   'netlink':
#     enabled:      0
#     name:         netlink

    'rrdtool': 
      enabled:      1
#     name:         rrdtool

rsyslog:
  active:       1
# confs:        { }
  monit:
    enabled:      1

logrotate:
  active:       1
  confs:
    'apt':
      enabled:      1
#     name:         apt

    'aptitude':
      enabled:      1
#     name:         aptitude

    'dpkg':
      enabled:      1
#     name:         dpkg

    'rsyslog':
      enabled:      1
#     name:         rsyslog

#   'monit':
#     enabled:      1
#     name:         monit

#   'collectd':
#     enabled:      1
#     name:         collectd

cron:
  active:       1
# crontab:      { }
# hourly:       { }
# daily:        { }
# weekly:       { }
# monthly:      { }
  monit:
    enabled:      1

openssh:
  active:       1
# address:      0.0.0.0
# port:         22
  monit:
    enabled:      1

ntp:
  active:       1
  monit:
    enabled:      1

iperf:
  active:       0
# server:       0
# address:      127.0.0.1
# port:         5281
# targets:      [ ]
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         5281
#   timeout:      10

qemukvm:
  active:       0
  monit:
    enabled:      1

dnsmasq:
  active:       0
# address:      127.0.0.1
# interface:    lo
# port:         53
# upstream:     [ 8.8.8.8, 8.8.4.4 ]
# conf:         { }
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         53
#   timeout:      10

unbound:
  active:       0
# address:      127.0.0.1
# port:         53
# allowed:      127.0.0.1/8
  conf:
    'qname-minimisation':
      enabled:      1
#     name:         qname-minimisation

    'root-auto-trust-anchor-file':
      enabled:      1
#     name:         root-auto-trust-anchor-file

  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         53
#   timeout:      10

nginx:
  active:       0
  conf:
    'cache':
      enabled:      1
#     name:         cache

    'gzip':
      enabled:      1
#     name:         gzip

    'resolver':
      enabled:      1
#     name:         resolver

    'ssl':
      enabled:      1
#     name:         ssl

    'cloudflare':
      enabled:      0
#     name:         cloudflare

# snippets:     { }
# secrets:      { }

  sites:
    'default':
      enabled:      1
#     name:         default
#     address:      127.0.0.1
#     port:         80
 
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         80
#   timeout:      10

mysql:
  active:       0
# address:      127.0.0.1
# port:         3306
# rootpw:       'secret'
# conf:         { }
  monit:
    enabled:      1

redis:
  active:       0
# address:      127.0.0.1
# port:         6379
  monit:
    enabled:      1
#   address:      127.0.0.1
#   port:         6379
#   timeout:      10
#   dumpsize:     100

postfix:
  active:       0
  monit:
    enabled:      1

certbot:
  active:       0
# options:      '--agree-tos'
# certs:        { }

rblcheck:
  active:       0
# hosts:        [ 127.0.0.1 ]
# lists:        [ zen.spamhaus.org ]
  monit:
    enabled:      1
#   timeout:      10

mmonit:
  active:       0
# version:      3.7.2
# platform:     linux-x64
# path:         /opt/mmonit
# address:      127.0.0.1
# port:         3127
# schema:       mysql://monit:monit@127.0.0.1/mmonit
# owner:        Unknown
# lecense:      none

rsync:
  active:       0
# address:      127.0.0.1
# port:         873
# storage:      /var/www/stuff

gitweb:
  active:       0
# projectroot:  /var/lib/git
# site_name:    Simple

freight:
  active:       0
# libdir:       /var/lib/freight
# cachedir:     /var/www/freight
# origin:       extradebs
# label:        Extradebs
# gpgkey:       build@extradebs

collectdweb:
  active:       0
# distrib:      https://github.com/httpdss/collectd-web.git
# workdir:      /var/www/collectd-web

